-- =================================================================
-- Banking Data Engineering Platform — Staging Schema DDL
-- =================================================================
-- These tables mirror the raw CSV files generated by the ingestion layer.
-- They act as a landing zone for data loaded from S3 before transformation.
-- All columns are VARCHAR or wide types to prevent load failures from bad data.
-- Data quality checks are run against this schema.

-- 1. Branches
CREATE TABLE IF NOT EXISTS staging.branches (
    branch_id VARCHAR(50),
    branch_name VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    branch_type VARCHAR(50),
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id VARCHAR(100)
);

-- 2. Merchants
CREATE TABLE IF NOT EXISTS staging.merchants (
    merchant_id VARCHAR(50),
    merchant_name VARCHAR(255),
    merchant_category VARCHAR(100),
    city VARCHAR(100),
    risk_category VARCHAR(50),
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id VARCHAR(100)
);

-- 3. Customers
CREATE TABLE IF NOT EXISTS staging.customers (
    customer_id VARCHAR(50),
    name VARCHAR(255),
    age VARCHAR(10),
    gender VARCHAR(20),
    city VARCHAR(100),
    state VARCHAR(100),
    occupation VARCHAR(100),
    income VARCHAR(50),
    account_open_date VARCHAR(50),
    customer_segment VARCHAR(50),
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id VARCHAR(100)
);

-- 4. Accounts
CREATE TABLE IF NOT EXISTS staging.accounts (
    account_id VARCHAR(50),
    customer_id VARCHAR(50),
    account_type VARCHAR(50),
    branch_id VARCHAR(50),
    balance VARCHAR(50),
    account_status VARCHAR(50),
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id VARCHAR(100)
);

-- 5. Transactions
CREATE TABLE IF NOT EXISTS staging.transactions (
    transaction_id VARCHAR(50),
    account_id VARCHAR(50),
    transaction_type VARCHAR(50),
    amount VARCHAR(50),
    timestamp VARCHAR(50),
    merchant_id VARCHAR(50),
    status VARCHAR(50),
    payment_method VARCHAR(50),
    channel VARCHAR(50),
    location VARCHAR(100),
    ingestion_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    batch_id VARCHAR(100)
);
